### ISSUE TITLE
Утвердить структуру ассемблера

### ISSUE THREAD

**Issue by CptnGreen** [CptnGreen/Corewar#21]
Прикинул, как должен работать наш ассемблер, получилось вот что:

![image](https://user-images.githubusercontent.com/20269405/87801165-fbc62c00-c857-11ea-9eb3-6e327acacde6.png)

Вносить правки можно по ссылке: https://drakonhub.com/ide/doc/corewar/3

Давайте обсудим - всё ли окей, что нужно добавить? 
Когда утвердим - создадим тикеты и распределим их между нами

**Comment by beskaska** [comment]
мое мнение по поводу схемы:
- не очень понимаю, какая нам будет нужна структура в init_asm(), полагаю такую же как 'header_t', только добавить лист из строк для хранения 'exec_byte_code' и переменную для его размера;
- думаю более целесообразно читать строку и тут же его обрабатывать, не собирая в список (не нашел информацию, обязательно ли 'name' и 'comment' должны идти впереди 'exec_code', если да, то +1 в пользу этого пункта);
- парсить 'name' и 'comment' можно в структуру типа 'header_t', которая уже объявлена в 'op.h';
- функция get_byte_code() должна уже вставлять фрагменты поочередно в файл .cor (без strjoin). 
- нет необходимости отдельно выводить функцию заполняющую нулями, функция chars_to_bytes() должна с этим справляться.

В итоге, пул задач в моем видении, на которые можно разбить asm в виде тикетов:
1. **main()** - проинициализировать структуру; открыть файл для чтения; проверить на расширение; прочитать файл построчно и каждую строку передавать в функцию handle_line(); закрыть файл для чтения; вызвать функцию get_byte_code(). Завершить работу.
2. **handle_line()** - если строка пустая или начинается с '#', игнорировать; если начинается с '.name' или '.comment', передать в функцию check_name_and_comment(); все другие строки обрабатывать в get_exec_code(); чистить строки.
3. **check_name_and_comment()** - сохранить все символы от кавычки до кавычки в соответствующем массиве структуры (если допускаются многострочные имена и комменты, то тут же читать следующие строки, пока не встретиться закрывающая кавычка). Контролировать максимально допустимую длину, иначе вернуть код ошибки.
4. **get_exec_code()** - преобразовывать в байт-код в соответствии с таблицей и хранить в листе структуры. Сообщить об ошибке при возникновении. Также контролировать максимально допустимую длину.
5. **get_byte_code()** - создать и открыть файл для записи; вставить magic_header; вызвать и вставить результат функции chars_to_bytes(prog_name); вставить нули-разделители; вставить prog_size (можно отдельной маленькой функцией); вставить результат функции chars_to_bytes(comment); вставить нули-разделители; вставить уже готовую  exec_code; закрыть файл для записи.
6. **chars_to_bytes()** - уверен, что с этой задачей может справиться наш принтф.

Как-то так. Надеюсь понятно. Реализовать до конца этой недели вполне реально. Мне только непонятно, как по нашей технике TDD тестировать такие функции как main и handle_line. По другим еще можно что-то придумать. Жду обратной связи)

**Comment by beskaska** [comment]
@CptnGreen а как изменять схему в ДРАКОНе, она read-only. Может ты там должен доступ дать?

**Comment by ellyellyd** [comment]
Прочла, что вы написали, ознакомилась с ссылками. Мне все ок, вопросов и предложений пока что нет

**Comment by CptnGreen** [comment]
@beskaska, хм, видимо для редактирования надо зарегаться и скинуть мне свой ник, чтобы я тебя добавил

**Comment by beskaska** [comment]
@CptnGreen ник beskaska

**Comment by CptnGreen** [comment]
@beskaska, добавил

@eels911, @ellyellyd, если хотите редактировать ДРАКОН-схемы, можете тоже зарегаться на drakonhub и скинуть свои ники - я вас добавлю в редакторы

**Comment by eels911** [comment]
пока все ок

**Comment by CptnGreen** [comment]
работа пошла, в целом кажется структура понятна. закрываю этот тикет
