### ISSUE TITLE
Написать main() ассемблера

### ISSUE THREAD

**Issue by beskaska** [CptnGreen/Corewar#24]
**Прототип**
`int	main(int argc, char **argv)`

**TO-DO**
- [x] написать функцию
- [x] написать тесты

**Описание**
Функция должна принимать список имен файлов с расширением ".s" и создавать соответствующие файлы с расширением ".cor". 

**Алгоритм**
- выделить память под структуру;
- для каждого аргумента:
	- инициализировать структуру нулями;
	- проверить расширение файла;
	- вызвать функцию handle_lines();
	- вызвать функцию print_byte_code();
- очистить структуру;
- завершить работу.

**Comment by CptnGreen** [comment]
@beskaska, @eels911, @ellyellyd, кто-то возьмёт на себя?

Просьба также указывать реалистичный дедлайн.

**Comment by beskaska** [comment]
Сама по себе функция легкая. Я не понимаю, как можно отдельно тестить `main()`, когда еще не готовы функций, вызываемые из `main()`. Прошу просветить, если есть идеи насчет этого.
А пока предлагаю начать работы с конечных функций, таких как:
- [get_name_and_comment()](https://github.com/CptnGreen/Corewar/issues/26) - @CptnGreen  уже взялся за эту функцию;
- [get_exec_code()](https://github.com/CptnGreen/Corewar/issues/20) - по мне это самая сложная часть асм, или я просто еще на разобрался. Я возьму его.
- [print_byte_code()](https://github.com/CptnGreen/Corewar/issues/4) - cейчас висит на @ellyellyd, возьмешься?
- [get_magic_header()](https://github.com/CptnGreen/Corewar/issues/5) - висит на @CptnGreen, думаю можно передать @eels911, либо отдать Эллаисе как составную часть `print_byte_code()`. Сабина, возможно она тебе покажется очень простой :)

После выше указанных функций нужно приступать к [handle_lines()](https://github.com/CptnGreen/Corewar/issues/25), а затем и к `main()`. Можно забирать по принципу "кто свободен".

Что скажете?

**Comment by ellyellyd** [comment]
@beskaska все пытаюсь влиться в процесс работы над кодом, стараюсь серьезнее взяться. Попробую написать функцию print_byte_code() и все необходимое для нее, хорошо. Можно распределять задачи по принципу кто свободен, я не против

**Comment by ellyellyd** [comment]
Предлагаю проработать описание функции и добавить [ ] чекбоксы, чтобы было удобнее отслеживать прогресс и готовность функции (вроде того, что я сделала в своей функции print_byte_code, хотя и там можно еще улучшить).

Для проверки расширения файлов можешь использовать мою функцию check_extension: ей поступает название файла с расширением, она проверяет с конца стоит ли там "s" а затем ".", если это не так, то возвращает -2, если все хорошо, то возвращает i (число), после которого начинается ".s" .

Если что, моя функция print_byte_code возвращает OK- все хорошо;  KO- произошла ошибка (OK=1; KO=0).

**Comment by ellyellyd** [comment]
задача выполнена, закрыла тикет
