### ISSUE TITLE
Написать функцию handle_lines()

### ISSUE THREAD

**Issue by beskaska** [CptnGreen/Corewar#25]
**Прототип**
`int	handle_lines(char *file_name, t_bot *bot)`

**TO-DO**
- [ ] написать функцию
- [ ] написать тесты

**Описание**
Функция должна прочитать файл, название которого она принимает в качестве параметра, и заполнить обработанной информацией структуру, которую также принимает в качестве параметра.

**Алгоритм**
- открыть файл для чтения;
- для каждой строки:
	- если строка пустая или начинается с '#' - игнорировать;
	- иначе, если строка начинается с '.name', передать строку в функцию get_name_and_comment()
	- иначе, если строка начинается с '.comment', передать строку в функцию get_name_and_comment()
	- иначе передать строку в функцию get_exec_code();
	- чистить строку;
- закрыть файл для чтения

**Comment by CptnGreen** [comment]
@beskaska, @eels911,@ellyellyd, кто возьмёт на себя? 

Просьба также указать реалистичный дедлайн.

**Comment by beskaska** [comment]
Немного потестил с приложенной асм, и вот:
- _.name_ и _.comment_ **всегда** должны идти вперед исполняемого кода;
- порядок _.name_ и _.comment_ могут меенятся между собой;
- команды _.name_ и _.comment_ обязательны (вместе с кавычками);
- пустые строки игнорируются в любых местах (аналогично с комментариями).

в связи с этим можно немного упростить алгоритм в описаниях
