### ISSUE TITLE
Написать функцию get_name_and_comment()

### ISSUE THREAD

**Issue by beskaska** [CptnGreen/Corewar#26]
**Прототип**

``` c
int	get_name_and_comment(char *src, char *dist, size_t max_len, size_t fd);
```

**TO-DO**

- [x] определиться, возможны ли многострочные имена и комментарий! [Возможны]
- [x] написать тесты
- [x] написать функцию

**Описание**

Функция должна записать все символы между кавычками из строки `src` в строку `dst`, переданных в качестве параметров.

**Алгоритм**

- если следующий непробельный символ открывающаяся кавычка:
	- для каждого символа до закрывающей кавычки:
		- записать символ в `dst`;
		- следить за максимально допустимой длиной `dst`;
		- если конец строки `src`:
			- прочитать новую строку;
			- рекурсивно запустить текущий цикл;
			- очистить строку;
			- выйти из цикла;
- иначе ошибка.

**Comment by beskaska** [comment]
для Error Management:
- нужно проверять символы после закрывающейся кавычки

**Comment by CptnGreen** [comment]
Возьму на себя
Deadline: 24.07 12:00

**Comment by CptnGreen** [comment]
@beskaska, не очень понимаю, зачем в прототипе `fd`?

**Comment by beskaska** [comment]
@CptnGreen чтобы читать строки. Если имя бота и/или комментарий будут многострочными, необходимо читать следующие строки до закрывающей кавчки.

**Comment by CptnGreen** [comment]
> Возьму на себя
> Deadline: 24.07 12:00

Начал, но не доделал
Новый дедлайн: 26.07 12:00

**Comment by CptnGreen** [comment]
Пример бота с многострочным комментарием лежит в:

`resources/vm_champs/championships/2014/hmotaou/Misaka_Mikoto.s`

**Comment by CptnGreen** [comment]
Разбил функцию на две: 
- вспомогательную `get_name_or_comment()` и 
- основную `get_name_and_comment()`, которая пишет сразу в бота

Чтобы писать сразу "в бота" (в структуру `t_bot`) поменял у неё прототип на вот такой:
``` c
int		get_name_and_comment(t_bot *bot, char *line, size_t fd);
```

Функции уже работают, но их нужно ещё допиливать, работу над ними продолжу в ближайшее время.
