### ISSUE TITLE
Подправить функцию либы ft_lstdelone

### ISSUE THREAD

**Issue by beskaska** [CptnGreen/Corewar#33]
Необходимо добавить проверку на NULL второго параметра:

```
if (del)
	del((*alst)->content, (*alst)->content_size);
```

а то вылетает сегфолт

**Comment by CptnGreen** [comment]
Ок, посмотрю

**Comment by beskaska** [comment]
@CptnGreen посмотрел? Я у себя исправил, могу просто запушить.

> PS: Я честно говоря никогда не пользовался этими либфт-шными функциями для работы со списками, потому что всегда писал отдельные функции под конкретные структуры в конкретной задаче.

зря, а где же философия DRY?))

**Comment by CptnGreen** [comment]
Внёс исправления Еса в подмодуль `libft`, закрываю тикет
