### ISSUE TITLE
Написать get_magic_header()

### ISSUE THREAD

**Issue by CptnGreen** [CptnGreen/Corewar#5]
### Прототип

```
char	*get_magic_header(void);
```

### TO-DO

- [x] написать тест
- [x] написать саму функцию

### Описание
Функция должна преобразовать строку-константу COREWAR_EXEC_MAGIC, определенную в op.h, в байт-код, готовый для записи в файл, и вернуть его.

**Comment by beskaska** [comment]
Крутая функция!) Может эту строку просто задефайнить в хедере?

**Comment by CptnGreen** [comment]
@beskaska , пока что я специально стараюсь создавать как можно больше issues, чтобы стимулировать нашу команду к началу совместной работы : )

Создание модулей ceedling, написание тестов, работа с гитом - всё это лучше попробовать на простых функциях. Я думаю на сегодняшнем созвоне мы как раз этим и займёмся.

**Comment by beskaska** [comment]
@CptnGreen я тоже хотел просто коммент написать. Похоже, что уведомление тебе пришло только после того, как я пометил вопрос незавершенным. А просто на коммент уведомления приходят?

**Comment by CptnGreen** [comment]
Насчёт уведомлений на коммент ничего сказать не могу. Кажется, что не приходят. Возможно, это настраивается

**Comment by beskaska** [comment]
Думаю будет правильнее работат с объявленной константой из приложенного хедера (op.h).  Поэтому нам нужна данная функция. Хотя можно его включить как статитк функцию в файл `print_byte_code()`, так как возвращаемое значение будет всегда одним и тем же.

**Comment by ellyellyd** [comment]
функция не актуальна как я поняла, закрыла тикет
